### ISSUE TITLE
How feasible is CLJS compatibility?

### ISSUE THREAD

**Issue by atroche** [dm3/clojure.java-time#4]
Hi @dm3, you've done a great job with this project. You've clearly put a lot of thought into it, and put the effort in to document it thoroughly. Thanks!

What do you think that most difficult challenges would be for someone to make a completely compatible CLJC version of this library?

**Comment by dm3** [comment]
Thanks :)

I've thought about that a bit. You are probably aware of the [cljs-time](https://github.com/andrewmcveigh/cljs-time) effort that provides a [clj-time](https://github.com/clj-time/clj-time) compatible Clojurescript layer. What I thought as the easiest path forward for someone who wants to use Java 8 Date-Time API instead of Joda-Time *and* make use of the same code in Clojurescript, would be to reimplement Clj-Time on top of Java 8 Date-Time API. Then the Clojurescript part would already be there.

80% of Clojure.Java-Time is dealing with different types of things in the Java Date-Time API. There's none of that in Javascript. You could probably come up with an implementation for most of the functions exposed in the `java-time` namespace, but it wouldn't be easy.
That said, I do prefer the `java-time` API to `clj-time` so if someone (or future me) selects a sensible subset of the API and makes a Clojurescript wrapper - that will be great! :)
However, I see this effort as a separate library as there will be pretty much zero code reused.

Does this answer your question?

**Comment by dm3** [comment]
@atroche I'm closing this question.
