### ISSUE TITLE
Deprecate single segment ns

### ISSUE THREAD

**Issue by frenchy64** [dm3/clojure.java-time#91]
Does not work well with Graalvm: https://github.com/clj-easy/graal-build-time#single-segment-namespaces

Consider `java-time.api`.

**Comment by seancorfield** [comment]
When you rename the namespaces, you probably want to rename the group/artifact since right now it's `clojure.java-time/clojure.java-time` which is both repetitive and a bit misleading (since people might think it's somehow a core/Contrib library).

Then you wouldn't need to keep the old ns at all: folks could have **both** libs on their classpath and they wouldn't conflict, allowing them to `require` both and migrate from one to the other piecemeal. That's what I did with HoneySQL.

**Comment by frenchy64** [comment]
Thanks @seancorfield, added a notice at the top of the readme to attempt to dissuade any association with Clojure. Not going to take further action for now.

**Comment by seancorfield** [comment]
"This library has no relation Clojure's" -- missing `to`.

Thanks for adding the clarification.

We use this library quite a bit at work so it's good to see it getting some love, although we're sort of ambiguous about using a wrapper rather than plain interop in many cases (we've already migrated away from both `date-clj` and `clj-time`).

**Comment by frenchy64** [comment]
FWIW this command helped me get 80% of the way to migrating a large codebase.
```
git grep -l java-time | xargs sed -i '' 's/java-time/java-time.api/g'
```
